version: "3.9"

services:
  consumer_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - USE_DOCKER=1
      - POSTGRES_NAME=todo
      - POSTGRES_USER=emumba
      - POSTGRES_PASSWORD=emumbaa

  consumer_web:
    build: .
    command: gunicorn --config gunicorn_config.py consumer.wsgi:application --workers=1 --threads=2 --timeout=90 --capture-output --reload
    ports:
      - "8002:8000"

    environment:
      - USE_DOCKER=1
      - POSTGRES_NAME=todo
      - POSTGRES_USER=emumba
      - POSTGRES_PASSWORD=emumba
      - TZ=Asia/Karachi
    depends_on:
      - consumer_db

    networks:
      - kafka_network

networks:
  kafka_network:
    external:
      name: kafka_network
