version: "3.9"

services:
  consumer_db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - USE_DOCKER=1
      - POSTGRES_NAME=todo
      - POSTGRES_USER=emumba
      - POSTGRES_PASSWORD=emumbaa

  consumer_kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9098,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9098,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

    networks:
      - kafka_network

  consumer_zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2184:2181"

    networks:
      - kafka_network

  consumer_web:
    build: .
    command: gunicorn --config gunicorn_config.py consumer.wsgi:application --workers=1 --threads=2 --timeout=90 --capture-output --reload
    ports:
      - "8002:8000"

    environment:
      - USE_DOCKER=1
      - POSTGRES_NAME=todo
      - POSTGRES_USER=emumba
      - POSTGRES_PASSWORD=emumba
    depends_on:
      - consumer_db
      - consumer_kafka

    networks:
      - kafka_network

networks:
  kafka_network:
    external:
      name: kafka_network
